server:
  port: 10012   # 端口号
spring:
  application:
    name: zuul-service   # 网关服务名称
zuul:
  prefix: /api   # 访问网关路径的前缀（在映射路径的前面，一般用于区别开发的版本）
  routes:
    user-consumer:     #前面的是eureka服务注册列表中的名称，后面的是映射路径的名称
      path: /zuul/**
#    zuul-service01:       # 随意写的区分不同映射服务器的名称（只是区分不同的映射服务器）
#      path: /user-service-zuul/**    # 自定义映射服务器路径的名称（相当于key，外部访问这个地址会映射到下面的service-id这个value值。然后从eureka服务列表找到对应服务名称，进而负载均衡的请求一个服务器）
##      url: http://127.0.0.1:8093  # 这是写的固定映射url，可代替service-id。但是不能实现服务器的负载均衡和高可用，因为总是访问同一服务器
#      service-id: user-service     # eureka注册中心中要映射的服务名称，因为是双层map结构，所以可以实现负载均衡和高可用
#    zuul-service02:               # 搭建另一个映射服务器，这里就简单的映射同一服务了。简单测试下而已
#      path: /user-service-zuul-first/**
#      service-id: user-service    # 映射服务器名称简单的使用上面的，仅供测试

#  因为zuul是整合ribbon和hystrix的另一个客户端，所以我们需要自己导入spring-retry坐标，并且开启服务
  retryable: true
#  配置zuul的连接时间，一般不需要配置
#  host:
#    max-per-route-connections:
#    socket-timeout-millis:
#    connect-timeout-millis:
#  ignored-services: microservice-comsumer-movie-ribbon-withhystrix    # 这是表示某一个服务不允许代理，上面配置的是需要代理的
eureka:
  client:
    registry-fetch-interval-seconds: 5    # 获取注册列表的周期
    service-url:
#    eureka注册中心地址
      defaultZone: http://127.0.0.1:8090/eureka,http://127.0.0.1:8091/eureka,http://127.0.0.1:8092/eureka
  instance:
    prefer-ip-address: true   # 返回ip地址而不是hostname
    ip-address: 127.0.0.1      # 本机地址
ribbon:
  ConnectTimeout: 250 # 连接超时时间（ms），默认值为250ms
  ReadTimeout: 2000 # 通信超时时间（ms），默认值为2000ms
  OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
  MaxAutoRetriesNextServer: 2 # 对同一服务不同实例重试次数（同一服务下集群个数的重试次数）
  MaxAutoRetries: 2 # 对同一实例重试的次数（单个集群节点服务重试的次数）
# 开启熔断机制，超过六秒即开启熔断机制，网关内的时间排序：zuul的通信时间 > hystrix熔断时间 > retry重试时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
sc:
  jwt:
   secret: sc@Login(Auth}*^31)&chengxi%       # 登录校验的密钥
   pubKeyPath: D:/rsa/rsa.pub               # 公钥地址
   priKeyPath: D:/rsa/rsa.pri                # 私钥地址
   expire: 30                                 # 过期时间,单位分钟
